language: java
jdk: oraclejdk9
before_install:
  - openssl aes-256-cbc -K $encrypted_e8c13656a88c_key -iv $encrypted_e8c13656a88c_iv
    -in deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - echo -e "Host $DIST_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
deploy:
  - provider: releases
    api_key:
      secure: L7Fmf26yGklP5k40vWltGHcpJpvMhocjg3caKZlZY26SMqiSkVxbngpj2hQeRuZusHh2A6nv7xePmWGLv9kTVkCcOghsCg8ZZXg0xNDHWeNH0KczfGQOjopkrp79RPHVyrb/ORlSDuRqyTe/mz+naxrqIykOKjiu2EdQwXlHzXYVNOHfhNw3h97fz039iOIEfOiLX1d3jmVlBwHN0I0U4mjF4nUthTmTG8I/nitainNFuVNloOqRws+WNf82lNGoSeF26QbiytVdGKVkCs+QoKWuf0Wa/bX8qFxA7EUmeGyKMD0aCkFIP2VteTNlhZeKtiIVgpKbh6ZBcMIuCREdHDolwO02UDdf/5dfODWE67d8ITmb6OlrhkzLBi6pf2Pzw+6AWzU8QyGI7LwjuzGnHpsiivAiEy+72hQ5u6bdKCOWgxelU/PWSEU4I6uLWmNA0yGeg8ZzSHdZ/esH1aAoJTEvAOWHNrKdZ2v4zdP0WEh+dm3GX3ZHxrMQZHhaFTwSduB6oaow/4WYuau70hMkuF6yT7xH3r+bRxYnTE5evAcaJbMceBmN90Z9kTbYkw3MNo1vY22t8nBCunFAs4DL5swkHgaZ4Y+u5dEnCcj20MdemIHCEuecwVcTF2+gaDVLM7f63Nhgcx+WWFrEY1iKg0aMT32N+Hn3dUcLMoAuqfw=
    file_glob: true
    file: build/libs/*
    skip_cleanup: true
    on:
      all_branches: true
      tags: true
      repo: xebialabs-community/xlr-selenium-plugin
  - provider: script
    skip_cleanup: true
    script: rsync --update -raz -i $TRAVIS_BUILD_DIR/build/libs/*.jar $DIST_USER@$DIST_HOST:$DIST_PATH/${TRAVIS_REPO_SLUG#*/}/
    on:
      all_branches: true
      tags: true
      repo: xebialabs-community/xlr-selenium-plugin
notifications:
  slack:
    secure: R9rabV1tVHFE6+3EyNeM5FxPtcHA5kJG+ta1NsbY8jhkoTB/JC+/Cm7TAFZrIbqYJrbKgaAnimDyhb8vnyTYT4zXrIZyulOaKHhf75rueFG0zcg3I1N0DUCvgTmgnVhleFnlRLfNlWpULjHLgNn379Rvn3/lFEQkx8hpLrZd6i+zsjFhePIRLLkxmrCYoNjeQ7yjtBOX6aJU2PfhbBnRafC36m4FuDJWtGO0sJRu9soN5fJCuSleqz9/KliYR4jtjO6bWqOrXvFWnLn8wg1dIjQKpp4+qgkd2eOPd6dWHl2y93nT1QXYW7TOLjLGd6CwC/lQAVufSv9yz4fze5YMLIKnAxWcCfaPY7XQBMliKKsTb3JtZ2n2HAPK1+GOzoMZE3StUs+ID9d2+7RJaXDQfOfHjfUteya8Cz88H6KEZ5wML815S6oDPDKxIMjUq+R6W3wi0lbkO14F5jo86nu3SxwAOSREemdRzpBIeXJtCLAJhXdE1n9EqUH03NVehNMKuQtwlQEoMw3MIzWkg4JjP7XGtqWtX1X72Qc0dIDcgWNJwrVEIWk4hDzFQU862tIfLRUWEveJledNJ44AAq5O6K6MRG3DQd3ikR/uWD4aCDgQER+9DOwvqNPOvrMbAm346eQki7X13Co0yCyhL01Q6DasHpnOkG4Cg1osO4iz4S0=
